### ISSUE TITLE
Does wucuo work with Flymake?

### ISSUE THREAD

**Issue by ParetoOptimalDev** [redguardtoo/wucuo#19]
I'm guessing not since it tries to update more conservatively to be faster, but figured I'd ask.

**Comment by redguardtoo** [comment]
it's possible but not worth the time. Since flyspell already provides UI.

**Comment by ParetoOptimalDev** [comment]
Okay, thank you. I prefer having one diagnostic buffer with my lints, so if it ever annoys me enough I'll send a PR 😃
